# Generated by Django 3.0.4 on 2020-12-20 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Sil')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı Soyadı')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yaşı')),
                ('phone', models.CharField(max_length=50, verbose_name='Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('address', models.CharField(max_length=200, verbose_name='Adresi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Sil')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Konu')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('duration', models.DurationField(verbose_name='Süre')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasyon')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Sil')),
                ('is_ok', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('is_visit', models.BooleanField(default=False, verbose_name='Ziyaret edildi')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
    ]
