# Generated by Django 3.0.4 on 2020-12-20 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201221_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 23, 7, 50, 287814, tzinfo=utc), verbose_name='Bitiş'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 23, 8, 3, 807669, tzinfo=utc), verbose_name='Başlangıç'),
            preserve_default=False,
        ),
    ]
