# Generated by Django 3.0.4 on 2020-12-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201221_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='subject',
            new_name='title',
        ),
    ]
